query getPoolSwaps($first: Int $skip: Int, $pool_id: Bytes, $start_date:BigInt, $end_date:BigInt) {
  swaps(
    first: $first
    skip: $skip
    where: {pool_: {id: $pool_id}, timestamp_gte: $start_date, timestamp_lte: $end_date}
  ){
    amountInUSD
    amountOutUSD
    amountIn
    amountOut
    account{
      id
    }
    timestamp
    blockNumber
    id
  }
}