query PairDayData($start_date: Int!, $end_date: Int!, $dailyVolumeUSD_gt: Int!, $dailyTxns_gt: Int!) {
  pairDayDatas(
    first: 1000,
    where: {
      AND: [
        {
          date_gt: $start_date
        },
        {
          date_lt: $end_date
        },
        {
          dailyVolumeUSD_gt: $dailyVolumeUSD_gt
        },
        {
          dailyTxns_gt: $dailyTxns_gt
        }
      ]
    }
  ) {
    id
    date
    pairAddress
    dailyVolumeUSD
    dailyTxns
    token0 {
      totalLiquidity
      txCount
    }
    token1 {
      totalLiquidity
      txCount
    }
  }
}