query getActivePools($first: Int $skip: Int, $start_date:BigInt, $end_date:BigInt, $minVolumeUSD:BigDecimal) {
  liquidityPoolDailySnapshots(
    first: $first
    skip: $skip
    orderBy: dailyTotalVolumeUSD
    orderDirection: desc
    where: {
      dailyTotalVolumeUSD_gte: $minVolumeUSD
      timestamp_lte: $end_date
      timestamp_gte: $start_date}
  ) {
    timestamp
    dailyTotalVolumeUSD
    
    pool {
      
      symbol

      totalValueLockedUSD
      protocol {
        name
        network
      }
      name
      id
      inputTokens {
        symbol
        lastPriceUSD
        decimals
      }

    }    
  }
}