query getPoolEvents($first: Int $skip: Int, $pool_id: ID, $start_date:BigInt, $end_date:BigInt) {
  swaps(
    first: $first
    skip: $skip
    where: {pool_: {id: $pool_id}, timestamp_gte: $start_date, timestamp_lte: $end_date}
  ){
    amountInUSD
    amountOutUSD

    from
    to
    timestamp
    blockNumber
    id
  }

  withdraws(
    first: $first
    skip: $skip
    where: {pool_: {id: $pool_id}, timestamp_gte: $start_date, timestamp_lte: $end_date}
  ){
    amountUSD
    inputTokenAmounts

    from
    to
    timestamp
    blockNumber
    id
  }

  deposits(
    first: $first
    skip: $skip
    where: {pool_: {id: $pool_id}, timestamp_gte: $start_date, timestamp_lte: $end_date}
  ){
    amountUSD
    inputTokenAmounts

    from
    to
    timestamp
    blockNumber
    id
  }
}